using UnityEngine;
using System.Collections;

public class GameManager : MonoBehaviour {
	
	public GameObject player;
	private GameObject currentPlayer;
	private GameCamera cam;
	
	void Start () {
		cam = GetComponent<GameCamera>();
		SpawnPlayer(Vector3.zero);
	}
	
	// Spawn player
	private void SpawnPlayer(Vector3 spawnPos) {
		GameObject[] rag = GameObject.FindGameObjectsWithTag("Ragdoll");
		if (rag.Length == 0) {
			currentPlayer = Instantiate (player, spawnPos, Quaternion.identity) as GameObject;
			cam.SetTarget (currentPlayer.transform); 
		}
	}
	private void Update() {
		if (!currentPlayer) {
			if (Input.GetButtonDown("Respawn")) {
				SpawnPlayer(Vector3.zero);
			}
		}
	}
}
